In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/train-data/Train_data.csv


In [6]:
data = pd.read_csv("/kaggle/input/train-data/Train_data.csv")

In [7]:
data = data.replace("na",np.NaN)

In [8]:
data.iloc[:,2:] = data.iloc[:,2:].astype("float32")

데이터의 형태 파악

In [9]:
data.describe()

Unnamed: 0        aa_000        ab_000        ac_000        ad_000  \
count  57000.000000  5.700000e+04  13012.000000  5.376300e+04  4.282200e+04   
mean   38084.150860  6.130698e+04      0.720719  3.566436e+08  2.009135e+05   
std    21920.895362  2.332295e+05      2.987399  7.952168e+08  4.148309e+07   
min        1.000000  0.000000e+00      0.000000  0.000000e+00  0.000000e+00   
25%    19100.750000  8.620000e+02      0.000000  1.600000e+01  2.400000e+01   
50%    38110.500000  3.084200e+04      0.000000  1.540000e+02  1.260000e+02   
75%    57059.500000  4.895400e+04      0.000000  9.710000e+02  4.320000e+02   
max    75998.000000  4.294967e+07    134.000000  2.130707e+09  8.584298e+09   

            ae_000        af_000        ag_000        ag_001        ag_002  \
count  54580.00000  54580.000000  5.635900e+04  5.635900e+04  5.635900e+04   
mean       7.03745     11.346574  2.429240e+02  1.384938e+03  1.065763e+04   
std      168.33519    211.333908  2.114293e+04  5.793025e+04  1.880938e+05   
min        0.00000      0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
25%        0.00000      0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
50%        0.00000      0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
75%        0.00000      0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
max    21050.00000  20070.000000  3.376892e+06  1.047252e+07  1.914916e+07   

       ...        ee_002        ee_003        ee_004        ee_005  \
count  ...  5.635600e+04  5.635600e+04  5.635600e+04  5.635600e+04   
mean   ...  4.559042e+05  2.158420e+05  4.564682e+05  4.062258e+05   
std    ...  1.212902e+06  5.665084e+05  1.232304e+06  1.168405e+06   
min    ...  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    ...  3.007500e+03  1.184000e+03  2.758000e+03  3.696000e+03   
50%    ...  2.360090e+05  1.125990e+05  2.231020e+05  1.910740e+05   
75%    ...  4.403585e+05  2.194610e+05  4.689245e+05  4.046395e+05   
max    ...  7.793393e+07  3.775839e+07  9.715238e+07  5.743524e+07   

             ee_006        ee_007        ee_008        ee_009        ef_000  \
count  5.635600e+04  5.635600e+04  5.635600e+04  5.635600e+04  54355.000000   
mean   3.403512e+05  3.512570e+05  1.401595e+05  8.365227e+03      0.077785   
std    1.094184e+06  1.748334e+06  4.724586e+05  4.669516e+04      3.891536   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
25%    5.380000e+02  1.140000e+02  0.000000e+00  0.000000e+00      0.000000   
50%    9.390400e+04  4.124500e+04  3.888000e+03  0.000000e+00      0.000000   
75%    2.768690e+05  1.681080e+05  1.393195e+05  1.966000e+03      0.000000   
max    4.215944e+07  1.195801e+08  1.718575e+07  4.570398e+06    482.000000   

             eg_000  
count  54356.000000  
mean       0.179483  
std        7.603027  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max     1146.000000  

[8 rows x 171 columns]

In [10]:
data.head()

Unnamed: 0 class    aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  \
0       52803   neg   41386.0     NaN   508.0   488.0     0.0     0.0     0.0   
1       38189   neg   29616.0     NaN  1616.0  1490.0     0.0     0.0     0.0   
2       23291   neg  241352.0     NaN     NaN     NaN     NaN     NaN     0.0   
3       16862   neg    8100.0     NaN    86.0    76.0     0.0     0.0     0.0   
4       14055   neg    2290.0     NaN   636.0   448.0     0.0     0.0     0.0   

   ag_001  ...     ee_002     ee_003     ee_004    ee_005    ee_006    ee_007  \
0     0.0  ...   438088.0   202172.0   383094.0  392838.0  228526.0  104226.0   
1     0.0  ...   145524.0    72858.0   171332.0  308328.0  379466.0  213826.0   
2     0.0  ...  3617298.0  2477772.0  3631902.0  997462.0  436380.0  202002.0   
3     0.0  ...    66980.0    36658.0    91898.0   86634.0   60276.0   23616.0   
4     0.0  ...    11542.0     7394.0    14206.0   69592.0    3108.0     108.0   

     ee_008  ee_009  ef_000  eg_000  
0  122526.0  6924.0     0.0     0.0  
1    5764.0   292.0     0.0     0.0  
2  173850.0  1376.0     NaN     NaN  
3    7518.0     2.0     0.0     0.0  
4       6.0     0.0     0.0     0.0  

[5 rows x 172 columns]

결측치 처리 

In [11]:
data = data.fillna(-1)

In [12]:
data.drop("Unnamed: 0",axis=1,inplace=True)

데이터 분리 및 Index 초기화

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
trn, val = train_test_split(data, test_size=0.2,shuffle=True, stratify=data["class"], random_state=42)

In [15]:
valid = data.iloc[val.index,:]
train = data.iloc[trn.index, :]

In [16]:
train = train.reset_index(drop=True)
valid = valid.reset_index(drop=True)

In [17]:
train.head()

class   aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg  46976.0     0.0   128.0   124.0     0.0     0.0     0.0     0.0   
1   neg  39910.0    -1.0    70.0    66.0     0.0     0.0     0.0     0.0   
2   neg  43614.0    -1.0   152.0   144.0     0.0     0.0     0.0     0.0   
3   neg     60.0    -1.0     0.0    -1.0     0.0     0.0     0.0     0.0   
4   neg  38938.0    -1.0   460.0   150.0     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005     ee_006    ee_007  \
0     0.0  ...  176578.0   80224.0  141948.0  164404.0  1438208.0   32222.0   
1     0.0  ...  291494.0  110406.0  265298.0  254714.0   232414.0  182932.0   
2     0.0  ...  314196.0  146948.0  297180.0  274392.0   247178.0  193972.0   
3     0.0  ...     578.0     190.0     468.0     732.0      138.0       0.0   
4     0.0  ...  459428.0  220256.0  413674.0  334330.0   196244.0   92842.0   

     ee_008   ee_009  ef_000  eg_000  
0     520.0      0.0     0.0     0.0  
1  309914.0    264.0     0.0     0.0  
2  320904.0  43452.0     0.0     0.0  
3       0.0      0.0     0.0     0.0  
4   57548.0    268.0     0.0     0.0  

[5 rows x 171 columns]

In [18]:
valid.head()

class    aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000   ag_001  \
0   neg   39034.0    -1.0   132.0   108.0     0.0     0.0     0.0      0.0   
1   pos  349286.0    -1.0    -1.0    -1.0    -1.0    -1.0     0.0  26204.0   
2   neg   32400.0    -1.0   714.0   626.0     0.0     0.0     0.0      0.0   
3   neg  378224.0    -1.0    36.0    16.0     0.0     0.0     0.0      0.0   
4   neg   61174.0    -1.0     0.0    -1.0     0.0     0.0     0.0      0.0   

     ag_002  ...     ee_002     ee_003     ee_004     ee_005    ee_006  \
0       0.0  ...   154734.0    69690.0   165178.0   133902.0  443552.0   
1  735690.0  ...  5012822.0  1532928.0  3381640.0  4543016.0  655000.0   
2       0.0  ...   320846.0   168344.0   408888.0   330388.0  153806.0   
3       0.0  ...    53412.0    24186.0    43278.0    37390.0   48242.0   
4       0.0  ...   417030.0   213806.0   466264.0   560570.0  527686.0   

     ee_007    ee_008  ee_009  ef_000  eg_000  
0  691076.0    6636.0     0.0     0.0     0.0  
1  207038.0    3480.0     0.0    -1.0    -1.0  
2   65222.0   52630.0    32.0     0.0     0.0  
3  293878.0   30980.0   194.0     0.0     0.0  
4  293296.0  224894.0  2752.0     0.0     0.0  

[5 rows x 171 columns]

Target 변수 one-hot encoding

In [19]:
x_train = train.iloc[:,1:]
y_train = train["class"]
x_valid = valid.iloc[:,1:]
y_valid = valid["class"]
y_train = y_train.replace({"neg" : 0, "pos" : 1})
y_valid = y_valid.replace({"neg" : 0, "pos" : 1})

In [20]:
y_train

0        0
1        0
2        0
3        0
4        0
        ..
45595    0
45596    0
45597    0
45598    0
45599    0
Name: class, Length: 45600, dtype: int64

비용함수 선언

In [78]:
def cost(y_pred,y_true) : 
    cost = 0
    for i in range(len(y_pred)) : 
        if y_pred[i] != y_true[i] : 
            if y_true[i] == 1 : 
                cost += 500
            if y_true[i] == 0 : 
                cost += 10
    return cost

첫번째 모델 RandomForestClassifer

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
#n_jobs 컴퓨터의 코어 사용 

In [24]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [25]:
rf_pred = rf.predict(x_valid)

In [26]:
rf_pred

array([0, 1, 0, ..., 0, 0, 1])

In [27]:
y_valid.values


array([0, 1, 0, ..., 0, 0, 1])

In [28]:
cost(rf_pred,y_valid.values)


27720

In [52]:
rf_pred_proba = rf.predict_proba(x_valid)

두번째 모델: XGBoost 

In [29]:
from xgboost import XGBClassifier

In [30]:
xgb = XGBClassifier(max_depth = 10, learning_rate=0.05,n_estimators=1600,tree_method = "gpu_hist")


In [31]:
xgb.fit(x_train,y_train)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.05, max_delta_step=0, max_depth=10,
              min_child_weight=1, missing=nan,
              monotone_constraints='(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)',
              n_estimators=1600, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='gpu_hist', validate_parameters=1, verbosity=None)

In [32]:
xgb_pred = xgb.predict(x_valid)

In [33]:
cost(xgb_pred,y_valid.values)

19190

3번째 모델 lgb

In [34]:
from lightgbm import LGBMClassifier


In [35]:
lgb = LGBMClassifier(boosting_type='gbdt', num_leaves=1024, learning_rate=0.02, n_estimators=1500, device = "gpu")


In [36]:
lgb.fit(x_train,y_train)


LGBMClassifier(device='gpu', learning_rate=0.02, n_estimators=1500,
               num_leaves=1024)

In [37]:
lgb_pred = lgb.predict(x_valid)

In [38]:
cost(lgb_pred,y_valid.values)

22200

In [39]:
lgb_pred_proba = lgb.predict_proba(x_valid)
xgb_pred_proba = xgb.predict_proba(x_valid)

정규화

In [40]:
from sklearn.preprocessing import StandardScaler


In [41]:
sc = StandardScaler()

In [42]:
x_train.iloc[:,:] = sc.fit_transform(x_train.iloc[:,:])
x_valid.iloc[:,:] = sc.transform(x_valid.iloc[:,:])

4번째모델 딥러닝모델

In [43]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
def model_create() : 
    model = Sequential()
    model.add(Dense(512, input_dim=x_train.shape[1], activation = "relu"))
    model.add(Dropout(0.5))
    model.add(Dense(384, activation = "relu"))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation = "softmax"))
    model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["sparse_categorical_accuracy"])
    return model

KFold를 활용하여 모델 과적합 방지

In [46]:
from sklearn.model_selection import KFold
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
kf = KFold(n_splits=5, shuffle=True, random_state=41)
i = 1
# callbacks = [EarlyStopping(monitor='val_loss',patience=3,)]
callbacks = [EarlyStopping(monitor='val_loss',patience=5,),
             ModelCheckpoint(filepath='best_weight.hdf5', verbose=1,
                             save_best_only=True, mode='auto')]

In [47]:
preds_test = np.zeros((len(x_valid),2) ,dtype = np.float)
filepath = './best_weight.hdf5'
for train_index, valid_index in kf.split(x_train):
    X_train, X_valid = x_train.iloc[train_index, :], x_train.iloc[valid_index, :]
    Y_train, Y_valid = y_train[train_index] ,y_train[valid_index]
    model = model_create()
    model.fit(X_train, Y_train, batch_size=512, epochs=1000, verbose=1,validation_data=(X_valid, Y_valid), callbacks = callbacks)
    model.load_weights(filepath)
    preds_test_fold = model.predict(x_valid,batch_size = 256, verbose=1)     
#     preds_test_fold = np.reshape(preds_test_fold, (1299, ))
    preds_test += preds_test_fold
preds_test /= 5

Epoch 1/1000
60/72 [========================>.....] - ETA: 0s - loss: 0.1185 - sparse_categorical_accuracy: 0.9731
Epoch 00001: val_loss improved from inf to 0.04975, saving model to best_weight.hdf5
72/72 [==============================] - 0s 6ms/step - loss: 0.1104 - sparse_categorical_accuracy: 0.9752 - val_loss: 0.0497 - val_sparse_categorical_accuracy: 0.9884
Epoch 2/1000
56/72 [======================>.......] - ETA: 0s - loss: 0.0495 - sparse_categorical_accuracy: 0.9871
Epoch 00002: val_loss improved from 0.04975 to 0.03836, saving model to best_weight.hdf5
72/72 [==============================] - 0s 4ms/step - loss: 0.0505 - sparse_categorical_accuracy: 0.9875 - val_loss: 0.0384 - val_sparse_categorical_accuracy: 0.9900
Epoch 3/1000
61/72 [========================>.....] - ETA: 0s - loss: 0.0354 - sparse_categorical_accuracy: 0.9897
Epoch 00003: val_loss improved from 0.03836 to 0.03464, saving model to best_weight.hdf5
72/72 [==============================] - 0s 4ms/step - los

69/72 [===========================>..] - ETA: 0s - loss: 0.0380 - sparse_categorical_accuracy: 0.9893
Epoch 00003: val_loss did not improve from 0.02855
72/72 [==============================] - 0s 3ms/step - loss: 0.0393 - sparse_categorical_accuracy: 0.9893 - val_loss: 0.0288 - val_sparse_categorical_accuracy: 0.9909
Epoch 4/1000
70/72 [============================>.] - ETA: 0s - loss: 0.0305 - sparse_categorical_accuracy: 0.9898
Epoch 00004: val_loss improved from 0.02855 to 0.02705, saving model to best_weight.hdf5
72/72 [==============================] - 0s 3ms/step - loss: 0.0304 - sparse_categorical_accuracy: 0.9898 - val_loss: 0.0271 - val_sparse_categorical_accuracy: 0.9911
Epoch 5/1000
69/72 [===========================>..] - ETA: 0s - loss: 0.0288 - sparse_categorical_accuracy: 0.9907
Epoch 00005: val_loss improved from 0.02705 to 0.02541, saving model to best_weight.hdf5
72/72 [==============================] - 0s 3ms/step - loss: 0.0282 - sparse_categorical_accuracy: 0.9910

Epoch 6/1000
71/72 [============================>.] - ETA: 0s - loss: 0.0269 - sparse_categorical_accuracy: 0.9911
Epoch 00006: val_loss did not improve from 0.02372
72/72 [==============================] - 0s 3ms/step - loss: 0.0268 - sparse_categorical_accuracy: 0.9911 - val_loss: 0.0238 - val_sparse_categorical_accuracy: 0.9923
Epoch 7/1000
70/72 [============================>.] - ETA: 0s - loss: 0.0240 - sparse_categorical_accuracy: 0.9916
Epoch 00007: val_loss did not improve from 0.02372
72/72 [==============================] - 0s 3ms/step - loss: 0.0239 - sparse_categorical_accuracy: 0.9916 - val_loss: 0.0240 - val_sparse_categorical_accuracy: 0.9920
Epoch 8/1000
68/72 [===========================>..] - ETA: 0s - loss: 0.0234 - sparse_categorical_accuracy: 0.9922
Epoch 00008: val_loss improved from 0.02372 to 0.02326, saving model to best_weight.hdf5
72/72 [==============================] - 0s 3ms/step - loss: 0.0233 - sparse_categorical_accuracy: 0.9922 - val_loss: 0.0233 - val

In [48]:
preds_test

array([[9.99440551e-01, 5.59492642e-04],
       [1.08265937e-02, 9.89173388e-01],
       [9.99998641e-01, 1.36600027e-06],
       ...,
       [9.81753695e-01, 1.82463158e-02],
       [9.99406397e-01, 5.93658397e-04],
       [8.07391298e-05, 9.99919295e-01]])

In [49]:
cost(np.argmax(preds_test,axis=1),y_valid)

32310

In [50]:
preds_test

array([[9.99440551e-01, 5.59492642e-04],
       [1.08265937e-02, 9.89173388e-01],
       [9.99998641e-01, 1.36600027e-06],
       ...,
       [9.81753695e-01, 1.82463158e-02],
       [9.99406397e-01, 5.93658397e-04],
       [8.07391298e-05, 9.99919295e-01]])

In [51]:
lgb_pred_proba

array([[9.99999669e-01, 3.31465301e-07],
       [1.02295124e-07, 9.99999898e-01],
       [9.99999998e-01, 2.03766330e-09],
       ...,
       [9.99999737e-01, 2.62716513e-07],
       [9.99999919e-01, 8.09649840e-08],
       [5.07777406e-08, 9.99999949e-01]])

In [84]:
final_pred = 0.05*rf_pred_proba+ preds_test*0.1 + lgb_pred_proba*0.35 + xgb_pred_proba*0.5

In [85]:
np.argmax(final_pred,axis=1)

array([0, 1, 0, ..., 0, 0, 1])

In [86]:
cost(np.argmax(final_pred,axis=1),y_valid)

22180